### ISSUE TITLE
BUG: In the latest update, after merging maturity, the merge button still stays clickable

### ISSUE THREAD

**Issue by saikatdas0790** [dfinity/nns-dapp#1079]
![image](https://user-images.githubusercontent.com/7412443/176990922-f1fcd82f-998b-4dae-9683-363fbd93650d.png)

**Expectation**: Should get disabled

If we click merge in this state, we get an error that looks like this

![image](https://user-images.githubusercontent.com/7412443/176990948-81be1a7f-6f8a-4e2d-82e6-ca95cce12861.png)

**Comment by lmuntaner** [comment]
Thanks for the report.

Indeed, this was a regression. We'll fix it for the next release.
