### ISSUE TITLE
Instructions for following

### ISSUE THREAD

**Issue by JensGroth** [dfinity/nns-dapp#1084]
The following instructions say: "Following allows you to delegate your votes to another neuron holder. You still earn rewards if you delegate your voting rights. You can change your following at any time." 
Could you clarify what happens when you follow multiple neurons? Could you clarify that you only get voting rights if that neuron votes.
E.g. "Following allows you to delegate your votes to another neuron. You vote the same as that neuron votes, so you still get voting rewards as long as that neuron votes. You can change your following at any time. (There is also an opportunity to follow a group of neurons, see https://wiki.internetcomputer.org/wiki/Maximizing_Voting_and_NNS_Rewards for more information.)"

**Comment by peterpeterparker** [comment]
Generally speaking we are thinking on we can improve the UX to make NNS-dapp more easy to grasp and also how we can integrate "help" and other hints. Since this issue is open since a while, I gonna close it and would say we gonna have a look at this in this initiative.
