### ISSUE TITLE
Got allows a redirect to a UNIX socket

### ISSUE THREAD

**Issue by imhunterand** [dfinity/nns-dapp#1189]
The latest possible version that can be installed is ``11.8.2`` because of the following conflicting dependencies:
```
geckodriver@3.0.1 requires got@11.8.2
wdio-geckodriver-service@2.1.1 requires got@11.8.2 via geckodriver@3.0.1
```
The earliest fixed version is ``11.8.5``.

**Comment by peterpeterparker** [comment]
> The latest possible version

The latest possible version of what? which dependency? what issue? can you please provide more context?

**Comment by peterpeterparker** [comment]
Closing as no answer and request, as far as I understand, does not make sense here.
