### ISSUE TITLE
Clicking a link causes Web page to disappear

### ISSUE THREAD

**Issue by vporton** [dfinity/nns-dapp#2268]
When I click at:
* ICP Wallet
* Sign with Internet identity
* GitHub
all the text on the Web page disappears (only background remains).

So, https://nns.ic0.app/ is fully unusable.

**Comment by vporton** [comment]
Note JavaScript error
```
content.js:191 Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')
    at Content.regulateTooltipVisibility (content.js:191:322)
    at HTMLDocument.<anonymous> (content.js:130:18)
```
on Chromium Version 111.0.5563.110 (Official Build) snap (64-bit).

**Comment by vporton** [comment]
On Firefox, there is no bug.

**Comment by peterpeterparker** [comment]
Not sure I understand the flow that leads to the error.

What do you mean with:

> When I click at:
>
>    ICP Wallet
>    Sign with Internet identity
>    GitHub

What's "GitHub"?

In addition, where do you collect the following stacktrace?

> content.js:191 Uncaught TypeError: Cannot set properties of null (setting 'innerHTML')

Can you provide screenshots?

**Comment by vporton** [comment]
"GitHub" link is in bottom right corner.

Clicking any link causes the page to disappear.

I collected the stacktrace in the JS console.

Screenshot:
![image](https://user-images.githubusercontent.com/2900574/230601672-f2fed01c-3efe-4fc1-ab96-8b789c999d96.png)

**Comment by peterpeterparker** [comment]
Also do you have some plugin installed?

The stacktrace you collected mention `content.js` but, there is no such JS file delivered with NNS-dapp.

**Comment by vporton** [comment]
It is "Translator" browser extension that triggers the bug.

**Comment by peterpeterparker** [comment]
Thanks for the report and debugging, good to know!

Then nothing we can do unfortunately I think because we just render a link.
Therefore I'll close this issue.
