### ISSUE TITLE
Ability to merge neurons

### ISSUE THREAD

**Issue by jzxchiang1** [dfinity/nns-dapp#258]
I noticed there's a new button to split neurons.

If there could be an analogous button to merge neurons, that would make neuron management much easier for users. Especially because a bunch of neurons were probably spawned by users prior to the release of the "merge maturity" feature a couple months ago.

**Comment by ielashi** [comment]
Hi @jzxchiang1, this feature is being worked by the NNS team and, once it's available on the governance canister, we'll introduce support for it in the frontend dapp.

**Comment by jzxchiang1** [comment]
Thank you.

**Comment by peterpeterparker** [comment]
A [Merge neurons](https://forum.dfinity.org/t/merge-neuron-s-function/10366/23) feature is now available.
