### ISSUE TITLE
Runtime error - unreachable code on IOS mobile

### ISSUE THREAD

**Issue by ByronBecker** [dfinity/nns-dapp#2717]
I encountered the following error while logging into the NNS dapp on safari mobile.

![image](https://github.com/dfinity/nns-dapp/assets/17368530/5a93aa91-5d76-4cb5-87df-ed72e2b68cf7)

Timestamp: Fri, 16 Jun 2023 14:52:09 GMT

Request: {
  "method": "GET",
  "url": "https://nns.ic0.app/",
  "origin": "https://nns.ic0.app"
}

**Comment by peterpeterparker** [comment]
Thanks for the feedback.

I don't think it's related to NNS dapp, therefore I gonna close the issue but, before doing so I also gonna share your feedback with the service worker team as it looks like related and let them know.

**Comment by peterpeterparker** [comment]
Also note that I am assuming that it happened only once and that you can access NNS dapp. If not the case, of course please let me know!

**Comment by nathanosdev** [comment]
Hey @ByronBecker, is this a transient or a persistent issue for you?

**Comment by ByronBecker** [comment]
> Hey @ByronBecker, is this a transient or a persistent issue for you?

Sorry for the delayed response - this was a transient issue and only occurred once
