### ISSUE TITLE
Nns Dapp wants to connect to HID Device 

### ISSUE THREAD

**Issue by icdev2dev** [dfinity/nns-dapp#273]
**Reporting this error from mparikh on forum**:
"So I was trying out an innocuous feature on Nns Dapp – Add Hotkey.

After adding and removing an Hotkey, I was trying the Add HotKey function again on Chrome in Ubuntu 20.04.

At that point, I got these two pops.

![9319a73178902607962522746902a9c218601622](https://user-images.githubusercontent.com/93845174/144280113-7cf1dc88-1117-4154-b148-e3ecb224d716.jpeg)

![d84eec2795c7ace71b69b44bd081a5739f3a1deb](https://user-images.githubusercontent.com/93845174/144280545-7d4d23db-1612-402a-bcde-6e02d5cb6f33.png)
I have never connected the ledger wallet to the nns dapp. What gives?
I am unable to reproduce this behavior."

Not able to trace this in context of call stack.

**Comment by ielashi** [comment]
We identified the issue and this occurs when your session has expired. Essentially, there's a confusion in the app where it doesn't detect that your session has expired and the code path for hardware wallets gets executed. I'll have a fix for this shortly.
