### ISSUE TITLE
DFX_NETWORK=local ./config.sh error

### ISSUE THREAD

**Issue by cymqqqq** [dfinity/nns-dapp#2985]
I followed the local development instructions, and in the step "DFX_NETWORK=local ./config.sh", it prints:
![image](https://github.com/dfinity/nns-dapp/assets/8555534/27daa718-44c8-4c71-a6fd-70ebafd5ea50)
do I make a wrong operation anywhere?

**Comment by bitdivine** [comment]
The "bad substitution" sounds as if this is running using an old shell.  Which version of bash do you have installed?

**Comment by cymqqqq** [comment]
thanks, it works now.:)
