### ISSUE TITLE
Fix dapp routing

### ISSUE THREAD

**Issue by anthonymq** [dfinity/nns-dapp#309]
Hi everyone,

I wanted to vote on the roadmap proposals but I found it very painful because the medium article links to https://dashboard.internetcomputer.org/proposal/XXXXX and there is a button to vote on NNS which doesn't redirect to the proposal because routing is not working properly.
When you click on "vote on NNS" button you're redirected to https://nns.ic0.app/#/proposal/XXXXX which immediately redirects to /#/accounts.
Also when you click on a tab you always stay on /#/accounts.
With so much proposals to vote on, the nns dapp needs to be simplified and fix this issue to enable a maximum of participation.

Sincerly

**Comment by ielashi** [comment]
I believe @anishh2003 is working on a fix for this, which will be deployed very soon.

**Comment by nmattia** [comment]
> With so much proposals to vote on, the nns dapp needs to be simplified and fix this issue to enable a maximum of participation.

Hi @anthonymq ! We are working on this as we speak. Over the next few weeks, we'll incrementally push changes to the NNS dapp that will get rid of most rendering and navigation bugs. Once we're done with that we'll start rolling out some pretty nice UX changes that should make everyone's life easier.

[A lot is happening behind the scenes](https://github.com/dfinity/nns-dapp/pulls?q=is%3Apr) and should start landing in production very soon!

**Comment by ielashi** [comment]
The dapp routing should now be fixed in production.

**Comment by anthonymq** [comment]
Yep just tested ! LGTM !
