### ISSUE TITLE
Voting tab should be refined

### ISSUE THREAD

**Issue by anthonymq** [dfinity/nns-dapp#311]
Hi everyone,

We should use a different type of layout for this critical screen, maybe a list with filters. There is to much proposals to present them with cards and  a font so big.
Could we add a "find by id" feature too ?

Sincerly

**Comment by ielashi** [comment]
Hey Anthony, we're now in the process of rewriting the app. Expect a big UX overhaul in the coming weeks/months.

**Comment by peterpeterparker** [comment]
The voting detail screen has changed and improved - in my opinion - a lot since this issue was raised, therefore I gonna go on an close it. If you notice anything particular that should be still improved, please open new dedicated task. D'avance merci 😃
