### ISSUE TITLE
Redundant "Load more proposals"

### ISSUE THREAD

**Issue by JensGroth** [dfinity/nns-dapp#344]
The NNS frontend dapp, voting tab, displays a link to "load more proposals" even when there are no additional proposals to load.

**Comment by nmattia** [comment]
Thanks! We're fixing some issues issues with the dapp and will get to this soon.

**Comment by peterpeterparker** [comment]
Thanks for the input. In the new svelte implementation the "load more proposals" link won't appear anymore - no link, no problem 😉.

We have implemented an "infinite scroll" behavior that displays a spinner when fetching data. In addition, when there is zero proposals to display, a corresponding information will be displayed.

Link to the [source](https://github.com/dfinity/nns-dapp/blob/1179461db963630a06f9194d3a8096c09069626d/frontend/svelte/src/routes/Proposals.svelte#L135) of this implementation.

Therefore I close this issue, I think it is resolved with the new development.
