### ISSUE TITLE
Prevent crashing when using NNS dapp on mobile devices

### ISSUE THREAD

**Issue by RAW4RMCS** [dfinity/nns-dapp#388]
When using the the NNS dapp on my iPhone 12 pro, and navigate to the voting page, it crashes when scrolling down. I found a quick workaround to prevent this, maybe this quick-fix can be implemented in the live version?

To prevent it from crashing I scroll down slowly (in the hope it doesn’t crash) and then click on the proposal status and only leave “open” selected. Then is doesn’t crash anymore. Is it possible to use this selection by default?

I think it's this piece of code;
https://github.com/dfinity/nns-dapp/blob/e0c2161d83ae616fd25e47563a5ecffa88552341/frontend/dart/lib/ui/proposals/governance_tab_widget.dart#L47

**Comment by nmattia** [comment]
Hi @RAW4RMCS, thanks for bringing this up!

This is unfortunately a known issue. We're working on a complete rewrite of the NNS app which we're rolling out incrementally. The next increment is the voting page, exactly for this reason. 

@ielashi @bitdivine @peterpeterparker what do you think of the workaround suggested above in the meantime?

**Comment by ielashi** [comment]
Thanks @RAW4RMCS!

@nmattia I think it's reasonable to only show open proposals as a stop-gap measure until the new voting page is introduced. @hpeebles any objections?

**Comment by hpeebles** [comment]
Sounds fine to me!
