### ISSUE TITLE
Canister Details Disappear while user tries to interact with the `Change Controllers` button

### ISSUE THREAD

**Issue by canselcik** [dfinity/nns-dapp#440]
Here is a screen capture of this happening:
https://streamja.com/JGGJJ

Workaround of positioning the cursor above where the button would be to click on it before it disappears is a workaround that seems to work well enough for now.

I had this happen on any browser I can think of on OSX and Linux. Haven't tested on Windows but no reason to believe it would be different.

**Comment by nmattia** [comment]
Hi, thanks for the report! we're rewriting the entire app and will be rolling out the new version tab by tab; we're starting with the proposals tab, but @bitdivine @peterpeterparker should we focus on the canister tab next? Seems like an annoying issue to have.

@lmuntanerDfinity can tell you more about the rewrite timeline

**Comment by lmuntanerDfinity** [comment]
Hi @canselcik !

As @nmattia mentioned, we are working on a full rewrite. I am preparing an article that we will publish with more details.

If this becomes a huge nuance, we could fix it in the current app, but we are prioritizing the rewrite.

I will share the article as soon as we publish it.

**Comment by canselcik** [comment]
Sounds like a plan. Yeah, I just wanted to make sure you guys were aware of it. Especially since a lot comes down to perception and optics these days. I wouldn't want the project to get a bad reputation due to small non-issue issues like this.

**Comment by lmuntanerDfinity** [comment]
Hi @canselcik ,

Here is the forum post regarding the rewrite I mentioned. Let me know if you have any question!

https://forum.dfinity.org/t/network-nervous-system-dapp-is-moving-to-svelte/11668
