### ISSUE TITLE
Info about proposals

### ISSUE THREAD

**Issue by JensGroth** [dfinity/nns-dapp#543]
In the current design the dapp displays title, proposer id and proposal id. 
I think it should display topic, since otherwise a proposal may be given a misleading title may lead me to believe it is for a different topic (and maybe I don't follow anybody for that category).
(And personally, proposer id and proposal id is not useful)

**Comment by lmuntanerDfinity** [comment]
I like the idea! I'll talke with the team.

**Comment by peterpeterparker** [comment]
The display of the information of the proposal has been now fully reworked which include using the topic as suggested to improve trust when reading the information.
