### ISSUE TITLE
Can't enter neuron detail page and proposal page (Uncaught TypeError)

### ISSUE THREAD

**Issue by zensh** [dfinity/nns-dapp#5540]
Uncaught (in promise) TypeError: Cannot destructure property 'default_followees' of 'object null'

<img width="1724" alt="image" src="https://github.com/user-attachments/assets/bf3652bd-3daf-48bb-a6d7-55ba2ca3e61e">

**Comment by dskloetd** [comment]
Thanks. Can you copy the URL here? It's a bit long to type from the screenshot.

Did you do anything in particular when this happened?

**Comment by zensh** [comment]
> Thanks. Can you copy the URL here? It's a bit long to type from the screenshot.
> 
> Did you do anything in particular when this happened?

Nothing

https://nns.ic0.app/proposal/?u=d7wvo-iiaaa-aaaaq-aacsq-cai&proposal=123&actionable

**Comment by dskloetd** [comment]
> https://nns.ic0.app/proposal/?u=d7wvo-iiaaa-aaaaq-aacsq-cai&proposal=123&actionable

This is not the URL I see at the top of the screenshot.

**Comment by dskloetd** [comment]
Did the error happen once? Every time? Sometimes? On load or when you perform some action? Does the page otherwise work? Not at all? Partially?

**Comment by zensh** [comment]
![Uploading image.png…]()
This page will throw error too

**Comment by dskloetd** [comment]
Thanks. I can repro.
