### ISSUE TITLE
Gap in proposal records

### ISSUE THREAD

**Issue by JensGroth** [dfinity/nns-dapp#741]
When I select all types of proposals the records are consecutive in the beginning, but then start having gaps. There is for instance a gap between 56187 Executed to 56138 Open, 56137 Open, 56134 Executed.
I find this puzzling, I was expecting a consecutive list (perhaps down to some cutoff, right now it goes all the way down to 340 Adopted)

**Comment by lmuntanerDfinity** [comment]
Do you have selected all the topics, with all the Proposal and Rewards status?

It works for me, see video below:

https://user-images.githubusercontent.com/98735375/165242164-9d620868-a56e-4e8f-9261-614e7e22399d.mov

**Comment by JensGroth** [comment]
I did indeed, but now 56187 disappeared. Here are some screenshots showing selection of topics and a gap in the records.
<img width="960" alt="Screen Shot 2022-04-26 at 9 26 01 AM" src="https://user-images.githubusercontent.com/46536510/165245551-754db600-2ef5-4b61-98dd-aa98b1e09474.png">
<img width="851" alt="Screen Shot 2022-04-26 at 9 25 38 AM" src="https://user-images.githubusercontent.com/46536510/165245564-89af9fdf-7e75-4214-b102-ee9fc82f8f4c.png">

**Comment by lmuntanerDfinity** [comment]
I see a few gaps, you are right.

It seems that the canister doesn't return those proposals.

For example, if I go to the proposal detail page: `https://nns.ic0.app/v2/#/proposal/56187` there is an error and the details are not displayed.

If I inspect the call, it seems that it doesn't find the proposal with that number.

@mstrasinskis any idea why these gaps might happen?

**Comment by peterpeterparker** [comment]
There were no similar report and the dapps has changed a lot as well since this issue has been raised, therefore I'll close it. If you still think there is an issue, please let us know.
