### ISSUE TITLE
Proposed improvement to voting on the Proposals pane

### ISSUE THREAD

**Issue by jwiegley** [dfinity/nns-dapp#927]
As of today, when I have lots of open proposals that I want to manually vote on, it is a rather arduous procedure:

1. Visit the "Voting" pane.
2. Click on the "Hide ineligible" checkbox.
3. Click on the first visible proposal, wait for it to load (several seconds).
4. Scroll down to the bottom.
5. Click Accept or Reject.
6. Click that yes, I'm sure.
7. Wait several seconds.
8. Press the little "Back" button in the upper left of the window.
9. Repeat.

My suggestion is to change this page entirely, or allow for an "advanced" voting mode. It would work like this:

1. "Hide ineligible" is the default.
2. Every proposal has a disclosure triangle next to it to reveal the whole summary *on that same page*. This way, I don't have to click anything to read further.
3. Every proposal has a radio button next to it: yes/no. This allows me to bulk select yes or no for every eligible, open proposal.
4. At the bottom is a single button "Submit votes", that does not prompt for confirmation. Or maybe it does, but I can mark a checkbox to remove the confirmation in future. It then proceeds to submit my votes, proposal by proposal.

This would allow me to very quickly vote on dozens of proposals without every leaving the proposals page, and without having to wait for network acknowledgement of the vote for each proposal before moving on to vote on the next.

**Comment by peterpeterparker** [comment]
The proposal detail page, deferred voting user experience and navigation between proposals have been reworked. 
Therefore I think we can close this issue. Feel free of course to open a new one with adapted suggestions if some would have not been solved with all these improvements.
