### ISSUE TITLE
Manage neurons error

### ISSUE THREAD

**Issue by JensGroth** [dfinity/nns-dapp#943]
I have a neuron which still follows some 'manage neuron'. When I try to change following I get this error message: 
Sorry, there was an unexpected error. Please try again later. Account with principal aaaa-bbbbb-ccccc-ddddd-eeeee-fffff-ggggg-hhhhh-iiiii-jjjjj-kkk not found!

I don't think that's a useful error message. Will trying again ever resolve the issue or are we just waisting the user's time? What is the user supposed to do or where can they learn what the problem is? Will users in general know what this principal is and where to find it?

**Comment by lmuntaner** [comment]
Fixed in https://github.com/dfinity/nns-dapp/pull/945
